# Generated by Django 4.2.25 on 2026-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveuser',
            name='code',
            field=models.CharField(blank=True, db_column='Code', max_length=50, null=True),
        ),
    ]
